name: JSON check

on:
  push:
    paths:
      - "**.json"
  pull_request:
    paths:
      - "**.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
      - name: python setup
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.10'
      - name: validate json using python
        run: |
          python -m pip install jsonschema
          python scripts/ValidateJson.py
